In [67]:
import pandas as pd
import matplotlib.image
import os
import numpy as np


In [52]:
os.chdir(r'../../')
train_image_path = r'data/raw/train/images'
test_image_path = r'data/raw/test/images'


In [32]:
train_image_list = [f for f in os.listdir(train_image_path)
                                   if f.endswith('.png')]
test_image_list = [f for f in os.listdir(test_image_path)
                                   if f.endswith('.png')]

print('number of train image:',len(train_image_list))
print('number of test image:',len(test_image_list))

number of train image: 4000
number of test image: 18000


In [23]:
train = pd.read_csv(r'data/raw/train.csv',index_col=None)

In [24]:
train.shape

(4000, 2)

In [25]:
train.id.unique().shape

(4000,)

In [27]:
depths = pd.read_csv(r'data/raw/depths.csv',index_col=None)

In [30]:
depths.shape

(22000, 2)

In [31]:
depths.id.unique().shape

(22000,)

In [34]:
train_depths = depths[depths.id.isin(train.id.unique())]
test_depths = depths[~depths.id.isin(train.id.unique())]


In [37]:
print(train_depths.shape)
print(test_depths.shape)

(4000, 2)
(18000, 2)


In [40]:
train_depths.head()

id    z
0  4ac19fb269  306
1  1825fadf99  157
2  f59821d067  305
3  5b435fad9d  503
4  e340e7bfca  783

In [41]:
test_depths.head()

id    z
4000  353e010b7b  264
4001  5439dbbddf  557
4002  71bab9f311  846
4003  52551f7a80  610
4004  512d8d9997  577

In [42]:
train.head()

id                                           rle_mask
0  575d24d81d                                                NaN
1  a266a2a9df                                          5051 5151
2  75efad62c1  9 93 109 94 210 94 310 95 411 95 511 96 612 96...
3  34e51dba6a  48 54 149 54 251 53 353 52 455 51 557 50 659 4...
4  4875705fb0  1111 1 1212 1 1313 1 1414 1 1514 2 1615 2 1716...

In [44]:
train_image_list[0]

'000e218f21.png'

In [51]:
train_image_list

['000e218f21.png',
 '003c477d7c.png',
 '00441f1cf2.png',
 '0050766ae2.png',
 '005b452274.png',
 '0061281eea.png',
 '008a50a2ec.png',
 '00950d1627.png',
 '00a3af90ab.png',
 '00cda0328c.png',
 '0108518d1e.png',
 '010ee525b6.png',
 '0115703825.png',
 '01323211a0.png',
 '016fc8031c.png',
 '019afb4b4e.png',
 '01b5362cce.png',
 '01c033e116.png',
 '01c2045d03.png',
 '020376e68e.png',
 '020678ec1b.png',
 '02117a400e.png',
 '021494f3aa.png',
 '02206b234e.png',
 '022b1b01be.png',
 '023d486fba.png',
 '0243477802.png',
 '0249c49180.png',
 '026b509cd4.png',
 '026f97575b.png',
 '0280db420c.png',
 '0280deb8ae.png',
 '029c321179.png',
 '02adf272e9.png',
 '02d40993ab.png',
 '03049b14ca.png',
 '0304e9ac37.png',
 '03511989ac.png',
 '0389fc6012.png',
 '03a9a9f615.png',
 '03be56aa9a.png',
 '03c9b5ffe8.png',
 '03eed26d3e.png',
 '0401ae15d3.png',
 '04182ced8e.png',
 '041925f04c.png',
 '04234be388.png',
 '0429d9759b.png',
 '042c3d4e03.png',
 '04315b9a64.png',
 '044106f759.png',
 '045c5516a2.png',
 '0461a2fb30

In [47]:

read_img = matplotlib.image.imread(os.path.join(train_image_path,train_image_list[0]))

In [144]:
def create_y(lt):
    if type(lt)!=str:
        return [0]*101*101
    else:
        result=[]
        for r in np.array(lt.split(' ')).reshape(-1,2):
            result.extend([0]*(int(r[0])-1-len(result)))
            result.extend([1]*(int(r[1])))
        result.extend([0]*(101*101-len(result)))
        return result
        

In [145]:
test = create_y(train.rle_mask.iloc[1])

In [150]:
train_image_list[0]

'000e218f21.png'

In [152]:


for image_id in train_image_list:
    train['rle_mask'][train.id==train_image_list.replace('.png','')]

3383    NaN
Name: rle_mask, dtype: object

'5051 5151'

'48 54 149 54 251 53 353 52 455 51 557 50 659 49 762 47 864 46 966 45 1068 44 1171 42 1273 41 1376 39 1478 38 1581 36 1683 35 1785 34 1888 32 1990 31 2092 30 2195 28 2297 27 2399 26 2501 25 2602 25 2704 24 2806 23 2907 23 3009 22 3110 22 3212 21 3313 21 3414 21 3516 20 3617 20 3718 20 3819 20 3921 19 4022 19 4123 19 4225 18 4326 18 4428 17 4529 17 4631 16 4733 15 4834 15 4936 14 5038 13 5140 12 5242 11 5344 8'

In [172]:
read_img




array([[0.5137255 , 0.5137255 , 0.5137255 , ..., 0.5411765 , 0.54509807,
        0.54509807],
       [0.5137255 , 0.5137255 , 0.5137255 , ..., 0.5411765 , 0.54509807,
        0.54509807],
       [0.5137255 , 0.5137255 , 0.5137255 , ..., 0.5411765 , 0.54509807,
        0.54509807]], dtype=float32)

In [156]:
read_img[0][0]

array([0.5137255, 0.5137255, 0.5137255], dtype=float32)

In [161]:
read_img[1][0]

array([0.5294118, 0.5294118, 0.5294118], dtype=float32)

In [162]:
read_img[2][0]

array([0.5294118, 0.5294118, 0.5294118], dtype=float32)

In [164]:
read_img[0][1]

array([0.5137255, 0.5137255, 0.5137255], dtype=float32)

In [165]:
read_img[0][2]

array([0.5137255, 0.5137255, 0.5137255], dtype=float32)